import type { Division, Project } from "../types";

/**
 * The three divisions. Copy is original to Tech Monkeys.
 */
export const divisions: Division[] = [
  {
    id: "01",
    segment: "startups",
    name: "Startups",
    focus: "Velocity",
    body: "First build, first customers, first raise. We take a founder’s idea to a product that ships, stands up to real users and reads as credible in the room.",
  },
  {
    id: "02",
    segment: "corporates",
    name: "Corporates",
    focus: "Scale",
    body: "For businesses whose spreadsheets have stopped coping. We replace manual process with systems that hold inventory, customers and orders in one place.",
  },
  {
    id: "03",
    segment: "enterprises",
    name: "Enterprises",
    focus: "Continuity",
    body: "Long-horizon work for organisations that cannot afford downtime. Connected platforms, monitoring and automation built to be maintained for years.",
  },
];

/**
 * Projects - every entry verified live on 2026-08-15.
 * See docs/project-inventory-verified.md for the audit.
 *
 * `nameApproved: false` on every entry: the client has not yet confirmed
 * which client names may be used publicly. lib/content.ts filters on it, so
 * the site renders an empty grid rather than publishing a name without
 * permission. Flip to true per project once confirmed.
 *
 * TODO(client): outcome sentence, year and cover image for each.
 */
export const projects: Project[] = [
  {
    slug: "hyde-park-wood",
    name: "Hyde Park Wood",
    sector: "Trade Supply",
    scope: "Wholesale trade portal handling multi-customer catalogues, order tracking and automated invoicing.",
    segment: "corporates",
    category: "platforms",
    tags: ["Platform", "Orders", "Invoicing"],
    url: "https://b2-b-blinds.vercel.app",
    status: "live",
    nameApproved: false,
    featured: true,
  },
  {
    slug: "fixnex",
    name: "FixNex",
    sector: "PropTech",
    scope: "AI-assisted property maintenance platform with conversational booking, predictive scheduling and connected-sensor monitoring.",
    segment: "enterprises",
    category: "ai",
    tags: ["AI", "Platform", "IoT"],
    url: "https://fixnex.ae",
    status: "live",
    nameApproved: false,
    featured: true,
  },
  {
    slug: "taldo",
    name: "Taldo",
    sector: "Recruitment",
    scope: "Cross-border hiring platform pairing healthcare candidates with placements, with editorial and admin tooling behind it.",
    segment: "corporates",
    category: "platforms",
    tags: ["Platform", "CMS", "Admin"],
    url: "https://taldo-eta.vercel.app",
    status: "live",
    nameApproved: false,
    featured: true,
  },
  {
    slug: "saabri",
    name: "Saabri",
    sector: "Sales",
    scope: "CRM for lead capture, enquiry tracking and team handover across a distributed sales floor.",
    segment: "corporates",
    category: "platforms",
    tags: ["CRM", "Web"],
    url: "https://saabri-dun.vercel.app",
    status: "live",
    nameApproved: false,
  },
  {
    slug: "cloak",
    name: "Cloak",
    sector: "Events",
    scope: "Digital cloakroom running QR-issued tickets and live venue operations for high-volume nights.",
    segment: "startups",
    category: "platforms",
    tags: ["Platform", "QR", "Ops"],
    url: "https://cloak-bice.vercel.app",
    status: "live",
    nameApproved: false,
  },
  {
    slug: "continental-premium-properties",
    name: "Continental Premium Properties",
    sector: "Real Estate",
    scope: "Property platform spanning listings, enquiry capture and an operations backend for the sales team.",
    segment: "corporates",
    category: "web",
    tags: ["Web", "Listings", "Backend"],
    url: "https://continental-properties.vercel.app",
    status: "live",
    nameApproved: false,
    featured: true,
  },
  {
    slug: "sartawi-properties",
    name: "Sartawi Properties",
    sector: "Real Estate",
    scope: "Property discovery site with search, saved listings and agent routing.",
    segment: "corporates",
    category: "web",
    tags: ["Web", "Brand"],
    url: "https://sartawi-realestate-eosin.vercel.app",
    status: "live",
    nameApproved: false,
  },
  {
    slug: "ark-vision",
    name: "ARK Vision",
    sector: "Real Estate",
    scope: "Luxury property presence for the Dubai market, built around high-value listings.",
    segment: "corporates",
    category: "web",
    tags: ["Web", "Luxury"],
    url: "https://ark-realestate.vercel.app",
    status: "live",
    nameApproved: false,
  },
  {
    slug: "skyran",
    name: "SKYRAN",
    sector: "Real Estate",
    scope: "Property portal with filtered search and detail pages for a Dubai agency.",
    segment: "corporates",
    category: "web",
    tags: ["Web", "Search"],
    url: "https://skyran-amber.vercel.app",
    status: "live",
    nameApproved: false,
  },
  {
    slug: "da-realty",
    name: "Da Realty",
    sector: "Real Estate",
    scope: "Luxury listings site for the Dubai market.",
    segment: "corporates",
    category: "web",
    tags: ["Web"],
    url: "https://da-reality.vercel.app",
    status: "live",
    nameApproved: false,
  },
  {
    slug: "credence-realtor",
    name: "Credence Realtor",
    sector: "Real Estate",
    scope: "Agency site with property enquiry funnels.",
    segment: "corporates",
    category: "web",
    tags: ["Web"],
    url: "https://credence-realtor.vercel.app",
    status: "live",
    nameApproved: false,
  },
  {
    slug: "dmd-properties",
    name: "DMD Properties",
    sector: "Real Estate",
    scope: "Property marketing site with listing management.",
    segment: "corporates",
    category: "web",
    tags: ["Web"],
    url: "https://dmd-properties-real-estate.vercel.app",
    status: "live",
    nameApproved: false,
  },
  {
    slug: "hometrack",
    name: "Hometrack",
    sector: "Wealth Management",
    scope: "Advisory presence on a live production domain, built for enquiry generation.",
    segment: "corporates",
    category: "web",
    tags: ["Web"],
    url: "https://www.hometrack.ae",
    status: "live",
    nameApproved: false,
  },
  {
    slug: "pacific-pearl-hotels",
    name: "Pacific Pearl Hotels",
    sector: "Hospitality",
    scope: "Multi-page hotel presence covering rooms, booking intent and guest experience.",
    segment: "corporates",
    category: "web",
    tags: ["Web", "Booking"],
    url: "https://pacific-pearl-hotels.vercel.app",
    status: "live",
    nameApproved: false,
  },
  {
    slug: "autobreeze",
    name: "AutoBreeze",
    sector: "Car Rental",
    scope: "Premium rental site with fleet browsing and reservation enquiry.",
    segment: "startups",
    category: "web",
    tags: ["Web", "Fleet"],
    url: "https://autobreezecarrental.vercel.app",
    status: "live",
    nameApproved: false,
  },
  {
    slug: "vedic-group",
    name: "Vedic Group of Institutions",
    sector: "Education",
    scope: "Institutional site covering programmes, admissions and campus information.",
    segment: "corporates",
    category: "web",
    tags: ["Web"],
    url: "https://harshaltarwale.github.io/Vedic-Group-of-Institutions/",
    status: "live",
    nameApproved: false,
  },
  {
    slug: "enabled",
    name: "Enabled",
    sector: "Nonprofit",
    scope: "Community support platform connecting members with services and resources.",
    segment: "startups",
    category: "web",
    tags: ["Web", "Community"],
    url: "https://enabled-ngo.vercel.app",
    status: "live",
    nameApproved: false,
  },
  {
    slug: "mindforge",
    name: "MindForge",
    sector: "Marketing",
    scope: "Conversion-led agency site with a motion-heavy narrative structure.",
    segment: "startups",
    category: "web",
    tags: ["Web", "Motion"],
    url: "https://mindforge-marketing.vercel.app",
    status: "live",
    nameApproved: false,
  },
  {
    slug: "copilot-labs",
    name: "Copilot Labs",
    sector: "Technology",
    scope: "Product marketing site for a technology studio.",
    segment: "startups",
    category: "web",
    tags: ["Web"],
    url: "https://copilot-labs.vercel.app",
    status: "live",
    nameApproved: false,
  },
  {
    slug: "neuroholistic",
    name: "NeuroHolistic",
    sector: "Wellness",
    scope: "Commerce experience with live Stripe payments and programme enrolment.",
    segment: "startups",
    category: "ecommerce",
    tags: ["E-commerce", "Stripe"],
    url: "https://neuro-holistic.vercel.app",
    status: "live",
    nameApproved: false,
    featured: true,
  },
  {
    slug: "lumina",
    name: "Lumina",
    sector: "Direct-to-Consumer",
    scope: "Single-product blackout blind brand for the US market, with sizing configurator and guarantee flows.",
    segment: "startups",
    category: "ecommerce",
    tags: ["E-commerce", "DTC"],
    url: "https://lumina-eta-nine.vercel.app",
    status: "live",
    nameApproved: false,
  },
  {
    slug: "onlineblinds",
    name: "OnlineBlinds",
    sector: "Retail",
    scope: "Made-to-measure storefront with dimension-driven pricing.",
    segment: "corporates",
    category: "ecommerce",
    tags: ["E-commerce", "Configurator"],
    url: "https://online-blinds-express.vercel.app",
    status: "live",
    nameApproved: false,
  },
  {
    slug: "priceless-blinds",
    name: "Priceless Blinds",
    sector: "Retail",
    scope: "Window furnishing storefront serving the Dublin market.",
    segment: "corporates",
    category: "ecommerce",
    tags: ["E-commerce"],
    url: "https://priceless-blinds.vercel.app",
    status: "live",
    nameApproved: false,
  },
  {
    slug: "yournextblinds",
    name: "YourNextBlinds",
    sector: "Retail",
    scope: "Made-to-measure blinds and shutters storefront.",
    segment: "corporates",
    category: "ecommerce",
    tags: ["E-commerce"],
    url: "https://yournextblinds-frontend.vercel.app",
    status: "live",
    nameApproved: false,
  },
];
