"use client";

import Image from "next/image";
import { useEffect, useRef, useState } from "react";

import { Arrow } from "@/components/ui/shell";
import type { Project, ServiceCategory } from "@/lib/content";

/**
 * Logical viewport width the hover-embed renders at before being scaled
 * down to fit its tile — kept identical to `scripts/capture-project-
 * screenshots.mjs`'s own viewport, so the static cover and the live
 * hover-embed show the same layout rather than two different crops.
 */
const EMBED_WIDTH = 1280;

/** Display labels for the category shown in each tile's footer row. */
export const CATEGORY_LABEL: Record<ServiceCategory, string> = {
  web: "Website",
  mobile: "Mobile App",
  ecommerce: "E-commerce",
  platforms: "Platform",
  ai: "AI & Automation",
  brand: "Branding",
  seo: "SEO",
  cloud: "Cloud & Hosting",
  consulting: "Consulting",
  video: "Video & Film",
};

/**
 * One project in the /projects and homepage-work grids.
 *
 * Card anatomy follows the reference the client pointed at (tentwenty's
 * cases page): a large media block, the project name beneath it, a hairline
 * rule, then a metadata row. Theirs pairs category with a year; none of our
 * projects carry a `year` (verified across all 12 publishable entries), so
 * the right-hand slot shows the project's real `sector` instead of an
 * invented date.
 *
 * Media, in priority order:
 *
 *   1. `project.video` — a silent screen-recording, plays muted+looped on
 *      hover. Nothing has one yet; the field exists so dropping a file in
 *      /public and setting the path is the only change needed later.
 *   2. `project.image` — a static cover screenshot in /public, generated by
 *      `scripts/capture-project-screenshots.mjs`. The default view for
 *      every project that has one (all 12 publishable ones, currently).
 *   3. `project.url`, live — a real embed of the actual site, but now only
 *      on hover (pointer-fine devices only), replacing the screenshot
 *      rather than sitting underneath it from page load.
 *   4. A typographic panel, if a project has none of the above.
 *
 * This replaced an earlier version that mounted the live embed for every
 * visible tile via IntersectionObserver, as soon as it scrolled near the
 * viewport. Measured with a PerformanceObserver: 6 embeds on the homepage
 * blocked the main thread for 1.1s total (worst single block 550ms), 12 on
 * /projects for 1.4s — and Lenis drives scroll from a requestAnimationFrame
 * loop, so those blocks are exactly when scrolling visibly stalled. That
 * was the actual cause of a reported "page stops scrolling below the
 * services section" bug. A static screenshot costs nothing at runtime; the
 * live embed is now opt-in per hover instead of mandatory per scroll.
 *
 * Deliberately no stock video or stock photography anywhere in that chain.
 * Using media we don't hold a licence for on a client's commercial site is
 * a real legal exposure, and a generic stock clip would misrepresent the
 * work anyway — the same reason the service-page mockups are drawn rather
 * than sourced, and the reason the screenshots above are captured from the
 * real, live projects rather than downloaded from anywhere else.
 */
export function ProjectTile({
  project,
  wide,
  featured,
  index,
  onPointerEnter,
  onPointerLeave,
}: {
  project: Project;
  /** Full-bleed row rather than a half-width cell. */
  wide?: boolean;
  /**
   * Lead treatment: a taller frame and an editorial two-column caption
   * carrying the project's real `scope` sentence. Used for the first tile
   * so the page opens on one project rather than a uniform catalogue —
   * a grid where every cell is identical gives a visitor no route in.
   */
  featured?: boolean;
  /**
   * Position in the rendered list, for the `01 / 02 / 03` marker. Counts
   * the visible grid, so it stays sequential under a category filter
   * instead of exposing gaps from the full set.
   */
  index?: number;
  onPointerEnter?: () => void;
  onPointerLeave?: () => void;
}) {
  const [canHover] = useState(
    () =>
      typeof window !== "undefined" &&
      window.matchMedia("(hover: hover) and (pointer: fine)").matches,
  );
  const frameRef = useRef<HTMLDivElement>(null);
  const videoRef = useRef<HTMLVideoElement>(null);
  const [hovering, setHovering] = useState(false);
  const [loaded, setLoaded] = useState(false);
  const [failed, setFailed] = useState(false);
  const [box, setBox] = useState<{ w: number; h: number } | null>(null);

  // Measured once — needed for the hover-embed's fixed-viewport scale math,
  // not for mount timing (that's `hovering` now, not scroll position).
  useEffect(() => {
    const el = frameRef.current;
    if (!el) return;
    const ro = new ResizeObserver(([entry]) => {
      const { width, height } = entry.contentRect;
      if (width > 0 && height > 0) setBox({ w: width, h: height });
    });
    ro.observe(el);
    return () => ro.disconnect();
  }, []);

  // A blocked iframe never fires onError, so a timeout is the only signal —
  // only runs while actually hovering, since that's the only time the
  // embed is mounted at all now.
  useEffect(() => {
    if (!hovering || loaded || project.video || !project.url) return;
    const timer = setTimeout(() => setFailed(true), 8000);
    return () => clearTimeout(timer);
  }, [hovering, loaded, project.video, project.url]);

  function handleEnter() {
    onPointerEnter?.();
    setHovering(true);
    videoRef.current?.play().catch(() => {});
  }
  function handleLeave() {
    onPointerLeave?.();
    setHovering(false);
    const v = videoRef.current;
    if (v) {
      v.pause();
      v.currentTime = 0;
    }
  }

  const showEmbed =
    canHover && hovering && !project.video && project.url && !failed;

  return (
    <a
      href={project.url ?? "/#contact"}
      target={project.url ? "_blank" : undefined}
      rel={project.url ? "noreferrer" : undefined}
      onPointerEnter={handleEnter}
      onPointerLeave={handleLeave}
      className={`group block ${wide ? "sm:col-span-2" : ""}`}
    >
      <div
        ref={frameRef}
        // Every ratio here is 4:3 or wider, matching the 4:3 capture, so a
        // cover is either shown whole or trimmed off the bottom — never
        // pinched horizontally. The old `2.2/1` featured frame cut each
        // site's hero in half and is gone.
        className={`relative overflow-hidden bg-bone ${
          featured ? "aspect-4/3 md:aspect-video" : wide ? "aspect-video" : "aspect-4/3"
        }`}
      >
        {/* Media scales up fractionally on hover — transform only, so the
            grid never reflows. */}
        <div className="absolute inset-0 transition-transform duration-700 ease-out group-hover:scale-[1.03]">
          {project.video ? (
            <video
              ref={videoRef}
              src={project.video}
              muted
              loop
              playsInline
              preload="metadata"
              className="h-full w-full object-cover"
            />
          ) : project.image ? (
            // Captured at 2x (see the capture script), so next/image has
            // real pixels to work with and the cover stays sharp even in
            // the featured tile, which renders ~1360px wide on desktop.
            // `object-top` is what keeps each project's hero in frame: the
            // source is 4:3 and every tile is 4:3 or wider, so the only
            // crop that can ever happen is off the bottom.
            <Image
              src={project.image}
              alt={`${project.name} — homepage`}
              fill
              sizes={
                featured || wide
                  ? "100vw"
                  : "(min-width: 640px) 50vw, 100vw"
              }
              className="object-cover object-top"
            />
          ) : (
            <TypePanel project={project} />
          )}

          {showEmbed && box && (
            <>
              {/* Rendered at a fixed EMBED_WIDTH desktop viewport and scaled
                  to fit — matches the capture script's own viewport, so
                  hovering doesn't visibly re-crop the same page. */}
              <iframe
                src={project.url}
                title={`${project.name} — live site`}
                tabIndex={-1}
                onLoad={() => setLoaded(true)}
                aria-hidden="true"
                style={{
                  width: EMBED_WIDTH,
                  height: box.h / (box.w / EMBED_WIDTH),
                  transform: `scale(${box.w / EMBED_WIDTH})`,
                }}
                className={`pointer-events-none absolute left-0 top-0 origin-top-left border-0 transition-opacity duration-500 ${
                  loaded ? "opacity-100" : "opacity-0"
                }`}
              />
              {/* "Live" tag confirms to a hovering visitor that what's
                  loading underneath is the real site, not another static
                  image — the one place this component still says so. */}
              <span className="absolute right-3 top-3 flex items-center gap-1.5 rounded-full bg-ink/70 px-2.5 py-1 font-mono text-[9px] uppercase tracking-[.12em] text-white backdrop-blur-sm">
                <span
                  className={`h-1.5 w-1.5 rounded-full bg-accent ${loaded ? "animate-pulse" : ""}`}
                />
                {loaded ? "Live" : "Loading…"}
              </span>
            </>
          )}
        </div>

        {/* Accent wash on hover, tying the tile to the site's one accent. */}
        <div
          aria-hidden="true"
          className="pointer-events-none absolute inset-0 bg-accent/0 transition-colors duration-500 group-hover:bg-accent/10"
        />
      </div>

      {featured ? (
        // Editorial two-column caption. The right-hand column carries the
        // project's real `scope` sentence — the one place on this page a
        // visitor learns what the work actually was before clicking.
        <div className="mt-6 grid gap-x-10 gap-y-4 md:grid-cols-12">
          <div className="md:col-span-7">
            <IndexMark index={index} featured />
            <h3 className="mt-3 text-4xl font-black leading-[.95] tracking-[-.04em] text-ink transition-colors duration-300 group-hover:text-accent md:text-5xl lg:text-6xl">
              {project.name}
            </h3>
          </div>
          <div className="flex items-start justify-between gap-6 md:col-span-5">
            <p className="max-w-md text-base leading-relaxed text-muted">
              {project.scope}
            </p>
            <Arrow
              spin
              className="mt-1 shrink-0 text-faint transition-colors duration-300 group-hover:text-accent"
            />
          </div>
        </div>
      ) : (
        <div className="mt-5 flex items-start justify-between gap-4">
          <div className="min-w-0">
            <IndexMark index={index} />
            <h3 className="mt-2 text-2xl font-black tracking-[-.03em] text-ink transition-colors duration-300 group-hover:text-accent md:text-3xl">
              {project.name}
            </h3>
          </div>
          <Arrow
            spin
            className="mt-2 shrink-0 text-faint transition-colors duration-300 group-hover:text-accent"
          />
        </div>
      )}

      <div
        className={`flex items-center justify-between gap-4 border-t border-line-strong font-mono text-[10px] uppercase tracking-[.18em] text-muted ${
          featured ? "mt-8 pt-5" : "mt-4 pt-4"
        }`}
      >
        <span>{CATEGORY_LABEL[project.category]}</span>
        <span className="text-faint">{project.sector}</span>
      </div>
    </a>
  );
}

/**
 * The `01 / 02 / 03` marker above each project name.
 *
 * Sits above the name rather than over the screenshot deliberately: our
 * covers run from near-white (Taldo, Hyde Park Wood) to near-black
 * (FixNex), so any number overlaid on the image would need a scrim to stay
 * legible on both — and that scrim would dull the very thing the tile
 * exists to show. Above the name it is always ink-on-bone.
 */
function IndexMark({ index, featured }: { index?: number; featured?: boolean }) {
  if (index === undefined) return null;
  return (
    <span className="flex items-center gap-3 font-mono text-[10px] uppercase tracking-[.2em]">
      <span className="text-faint">{String(index + 1).padStart(2, "0")}</span>
      {featured && (
        <>
          <span className="h-px w-6 bg-line-strong" />
          <span className="text-accent-deep">Featured project</span>
        </>
      )}
    </span>
  );
}

/** Typographic stand-in for a project with neither an image nor a video. */
function TypePanel({ project }: { project: Project }) {
  return (
    <div className="flex h-full w-full flex-col items-center justify-center gap-3 bg-bone px-6 text-center">
      <span className="font-mono text-[10px] uppercase tracking-[.2em] text-accent-deep">
        {project.sector}
      </span>
      <span className="text-2xl font-black tracking-[-.03em] text-ink/25">
        {project.name}
      </span>
    </div>
  );
}
